<a href="https://colab.research.google.com/github/xEzIxX/AI-Class/blob/master/week2/breast_cancer_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np;

# 파일 경로 설정
# 이미 전문가에 의해 특징이 추출된 데이터
file_path = '/content/drive/MyDrive/Colab Notebooks/breast_cancer.csv';

# 데이터 읽기
df = pd.read_csv(file_path);

# 상위 5개 행 확인
# print(df.head());
df.head()

,Unnamed: 0,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,label
0,0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [4]:
y=df['worst compactness'];
print(y.value_counts());

worst compactness
0.3416    3
0.1486    3
0.3055    2
0.1963    2
0.2264    2
         ..
0.3299    1
0.1610    1
0.3547    1
0.7584    1
0.4056    1
Name: count, Length: 529, dtype: int64

In [5]:
y

0      0.66560
1      0.18660
2      0.42450
3      0.86630
4      0.20500
        ...
564    0.21130
565    0.19220
566    0.30940
567    0.86810
568    0.06444
Name: worst compactness, Length: 569, dtype: float64

In [6]:
df2=df.drop('worst compactness',axis=1) # worst compactness 열 삭제
df2.head()

,Unnamed: 0,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,label
0,0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.7119,0.2654,0.4601,0.11890,0
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.2416,0.1860,0.2750,0.08902,0
2,2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4504,0.2430,0.3613,0.08758,0
3,3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.6869,0.2575,0.6638,0.17300,0
4,4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.4000,0.1625,0.2364,0.07678,0

In [7]:
from sklearn.model_selection import train_test_split

# 25퍼센트를 테스트 케이스로 준다
# 75 퍼센트를 학습, 정답값이 없는 25퍼센트로 테스트 진행
X_train, X_test, y_train, y_test = train_test_split(df2, y,test_size=0.25,random_state=0)

In [8]:
X_test

,Unnamed: 0,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,label
512,512,13.40,20.52,88.64,556.7,0.11060,0.14690,0.14450,0.08172,0.2116,...,16.41,29.66,113.30,844.4,0.15740,0.51060,0.20510,0.3585,0.11090,0
457,457,13.21,25.25,84.10,537.9,0.08791,0.05205,0.02772,0.02068,0.1619,...,14.35,34.23,91.29,632.9,0.12890,0.13900,0.06005,0.2444,0.06788,1
439,439,14.02,15.66,89.59,606.5,0.07966,0.05581,0.02087,0.02652,0.1589,...,14.91,19.31,96.53,688.9,0.10340,0.06260,0.08216,0.2136,0.06710,1
298,298,14.26,18.17,91.22,633.1,0.06576,0.05220,0.02475,0.01374,0.1635,...,16.22,25.26,105.80,819.7,0.09445,0.15650,0.07530,0.2636,0.07676,1
37,37,13.03,18.42,82.61,523.8,0.08983,0.03766,0.02562,0.02923,0.1467,...,13.30,22.81,84.46,545.9,0.09701,0.04833,0.05013,0.1987,0.06169,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,236,23.21,26.97,153.50,1670.0,0.09509,0.16820,0.19500,0.12370,0.1909,...,31.01,34.51,206.00,2944.0,0.14810,0.58200,0.25930,0.3103,0.08677,0
113,113,10.51,20.19,68.64,334.2,0.11220,0.13030,0.06476,0.03068,0.1922,...,11.16,22.75,72.62,374.4,0.13000,0.12950,0.06136,0.2383,0.09026,1
527,527,12.34,12.27,78.94,468.5,0.09003,0.06307,0.02958,0.02647,0.1689,...,13.61,19.27,87.22,564.9,0.12920,0.17910,0.10700,0.3110,0.07592,1
76,76,13.53,10.94,87.91,559.2,0.12910,0.10470,0.06877,0.06556,0.2403,...,14.08,12.49,91.36,605.5,0.14510,0.08539,0.07407,0.2710,0.07191,1
162,162,19.59,18.15,130.70,1214.0,0.11200,0.16660,0.25080,0.12860,0.2027,...,26.73,26.39,174.90,2232.0,0.14380,0.68100,0.22470,0.3643,0.09223,0

In [9]:
# worst compactness 값의 오차를 추론

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(X_train, y_train) # 정답값 (worst compactness) 이 있는 train으로 학습
ly_preds = model.predict(X_test) # 정답값이 없는 X_test로 테스트 진행

# 평균 제곱근 오차를 세번 구하는 이유: 다양한 연산 방법을 사용해도 동일하게 나옴을 보여주기 위해

print("\n[Linear Regression Regressor 의 결과]\n")

# 방식 1: 사이킷런 표준 함수 사용
print('평균제곱근오차', mean_squared_error(ly_preds, y_test))

# 방식 2: 넘파이 배열 연산 활용
# (실제값 - 예측값)^2 의 평균을 구하는 MSE 수식 적용
def mse_np(actual, predicted):
    return np.mean((np.array(actual) - np.array(predicted)) ** 2)

print('평균제곱근오차', mse_np(ly_preds, y_test))

# 방법3: 파이썬 반복문-> 하나씩 꺼내서 오차를 더해감
def mse(actual, predicted):
    sum_square_error = sum((a - p) ** 2 for a, p in zip(actual, predicted))
    mean_square_error = sum_square_error / len(actual)
    return mean_square_error

print('평균제곱근오차', mse(ly_preds, y_test))

평균제곱근오차 0.0004940829358206368
평균제곱근오차 0.0004940829358206368
평균제곱근오차 0.0004940829358206369

In [10]:
from sklearn.tree import DecisionTreeRegressor

# 1. 모델 생성 및 학습
dt_model = DecisionTreeRegressor(random_state=0)
dt_model.fit(X_train, y_train) # 75% 학습 데이터로 나무 규칙 생성

# 2. 예측 진행
dt_preds = dt_model.predict(X_test) # 25% 테스트 데이터로 수치 추론

print("\n[Random Forest Regressor 의 결과]\n")

# 방식 1: 사이킷런 표준 함수 사용
print('평균제곱근오차', mean_squared_error(dt_preds, y_test))

# 방식 2: 넘파이 배열 연산 활용
print('평균제곱근오차)', mse_np(dt_preds, y_test))

# 방식 3: 파이썬 반복문 활용
print('평균제곱근오차', mse(dt_preds, y_test))

 [Random Forest Regressor 의 결과]
평균제곱근오차(MSE) 0.0076953601748251735
평균제곱근오차(NumPy) 0.0076953601748251735
평균제곱근오차(Loop) 0.007695360174825181

In [11]:
from sklearn.ensemble import RandomForestRegressor

# 1. 모델 생성 및 학습
rf_model = RandomForestRegressor(random_state=0)
rf_model.fit(X_train, y_train) # 여러 개의 나무가 각자 학습 진행

# 2. 예측 진행
rf_preds = rf_model.predict(X_test) # 모든 나무의 예측값 평균을 최종 답으로 채택

print("\n[Random Forest Regressor 의 결과]\n")

# 방식 1: 사이킷런 표준 함수 사용
print('평균제곱근오차', mean_squared_error(rf_preds, y_test))

# 방식 2: 넘파이 배열 연산 활용
print('평균제곱근오차', mse_np(rf_preds, y_test))

# 방식 3: 파이썬 반복문 활용
print('평균제곱근오차', mse(rf_preds, y_test))

[Random Forest Regressor 의 결과]

평균제곱근오차 0.00219169173441545
평균제곱근오차 0.00219169173441545
평균제곱근오차 0.002191691734415451