<a href="https://colab.research.google.com/github/xEzIxX/AI-Class/blob/master/week3/wine_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 와인 등급 classification

In [2]:
import pandas as pd
import numpy as np;

file_path = '/content/drive/MyDrive/Colab Notebooks/wine.csv';

# 데이터 읽기
df = pd.read_csv(file_path);

# 상위 5개 행 확인
# print(df.head());
df.head()

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [3]:
# 정답(label) 데이터 설정
# Wine = 와인 등급
y=df['Wine'];
print(y.value_counts());

Wine
2    71
1    59
3    48
Name: count, dtype: int64

In [4]:
# 입력 데이터(feature) 생성
# Wine을 맞춰야하니 해당 등급을 제외
X=df.drop('Wine',axis=1)
X.head()

,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [5]:
from sklearn.model_selection import train_test_split

# 학습 데이터 / 테스트 데이터 분리
# 25퍼센트를 테스트 케이스로 준다
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [6]:
# Logistic Regression 모델 생성
# 입력 특징을 이용하여 "당뇨일 확률"을 계산하고, 그 확률을 기반으로 0 또는 1로 분류하는 모델
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# 모델 학습 (훈련 데이터로 패턴 학습)
clf_lr = LogisticRegression(random_state=0) # 머신러닝 모델 빌드
clf_lr.fit(X_train, y_train) # 훈련

pred_lr = clf_lr.predict(X_test) # 예측한 값 입력

# 모델 성능 평가
print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr)) # 전체 예측 중 맞춘 비율
print (confusion_matrix(y_test, pred_lr)) # 실제값 vs 예측값 비교 행렬

--- Logistic Regression Classifier ---
0.9333333333333333
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [7]:
# Decision Tree 모델 생성
# 입력 feature 값을 기준으로 데이터를 분할하고
# 가장 잘 클래스가 구분되는 기준을 선택하여 트리 구조로 분류하는 모델
from sklearn.tree import DecisionTreeClassifier

# 모델 학습 (훈련 데이터로 분류 규칙 학습)
clf_dt = DecisionTreeClassifier(random_state=0) # 머신러닝 모델 빌드
clf_dt.fit(X_train, y_train) # 훈련

# 테스트 데이터로 클래스 예측
pred_dt = clf_dt.predict(X_test)

# 모델 성능 평가
print("\n--- Decision Tree Classifier ---")
print(accuracy_score(y_test, pred_dt)) # 전체 예측 중 맞춘 비율
print(confusion_matrix(y_test, pred_dt)) # 실제값 vs 예측값 비교 행렬

--- Decision Tree Classifier ---
0.9333333333333333
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]

In [8]:
# Random Forest 모델 생성
# 여러 개의 Decision Tree를 학습시킨 뒤, 각 트리의 예측 결과를 종합(투표)하여 분류하는 앙상블 모델
from sklearn.ensemble import RandomForestClassifier

# 모델 학습 (여러 Decision Tree 학습)
clf_rf = RandomForestClassifier(random_state=0)
clf_rf.fit(X_train, y_train)

# 테스트 데이터 예측
pred_rf = clf_rf.predict(X_test)

# 모델 성능 평가
print("\n--- Random Forest Classifier ---")
print(accuracy_score(y_test, pred_rf))  # 전체 예측 중 맞춘 비율
print(confusion_matrix(y_test, pred_rf))  # 실제값 vs 예측값 비교

--- Random Forest Classifier ---
0.9777777777777777
[[16  0  0]
 [ 0 20  1]
 [ 0  0  8]]

In [10]:
# KNN 분류 모델 생성
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=6) # 이웃을 6명으로 설정
knn_model.fit(X_train, y_train)

knn_preds = knn_model.predict(X_test) # 예측

# 모델 성능 평가
print("\n--- KNN Classifier ---")
print(accuracy_score(y_test, knn_preds))
print(confusion_matrix(y_test, knn_preds))

--- KNN Classifier ---
0.7111111111111111
[[14  0  2]
 [ 0 16  5]
 [ 2  4  2]]