<a href="https://colab.research.google.com/github/xEzIxX/AI-Class/blob/master/week3/wine_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 와인의 알콜값 regression

In [15]:
import pandas as pd
import numpy as np;

file_path = '/content/drive/MyDrive/Colab Notebooks/wine.csv';

# 데이터 읽기
df = pd.read_csv(file_path);

# 상위 5개 행 확인
# print(df.head());
df.head()

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [16]:
# 정답(label) 데이터 설정
# Alcohol = 알콜
y=df['Alcohol'];
print(y.value_counts());

Alcohol
13.05    6
12.37    6
12.08    5
12.29    4
12.00    3
        ..
12.82    1
12.20    1
14.16    1
13.27    1
14.13    1
Name: count, Length: 126, dtype: int64

In [17]:
# 입력 데이터(feature) 생성
# 알콜을 예측해야하니 해당 값을 제외
X=df.drop('Alcohol',axis=1)
X.head()

,Wine,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [18]:
from sklearn.model_selection import train_test_split

# 학습 데이터 / 테스트 데이터 분리
# 25퍼센트를 테스트 케이스로 준다
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [19]:
# 평균 제곱근 오차를 구하는 메서드 정의
def mse_np(actual, predicted):
    return np.mean((np.array(actual) - np.array(predicted)) ** 2)

def mse(actual, predicted):
    sum_square_error = sum((a - p) ** 2 for a, p in zip(actual, predicted))
    mean_square_error = sum_square_error / len(actual)
    return mean_square_error

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(X_train, y_train)
ly_preds = model.predict(X_test)

# 성능 평가
print("\n--- Linear Regressor ---")
print('평균제곱근오차', mean_squared_error(ly_preds, y_test))
# print('평균제곱근오차', mse_np(ly_preds, y_test))
# print('평균제곱근오차', mse(ly_preds, y_test))

--- Linear Regressor ---
평균제곱근오차 0.3511470189437248

In [11]:
# Decision Tree 회귀 모델
# feature 기준으로 데이터를 반복 분할하여
# 값의 평균을 이용해 연속값(BMI)을 예측하는 트리 기반 회귀 모델

from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor(random_state=0)

# 모델 학습
dt_model.fit(X_train, y_train)

# 예측
dt_preds = dt_model.predict(X_test)

# 성능 평가 (MSE)
print("\n--- Decision Tree Regressor ---")
print("평균제곱오차", mean_squared_error(y_test, dt_preds))

--- Decision Tree Regressor ---
평균제곱오차 0.558966666666667

In [12]:
# Random Forest 회귀 모델
# 여러 개의 Decision Tree를 생성하고
# 각 트리의 예측값 평균을 이용해 연속값을 예측하는 모델

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(random_state=0)

# 모델 학습
rf_model.fit(X_train, y_train)

# 예측
rf_preds = rf_model.predict(X_test)

# 성능 평가 (MSE)
print("\n--- Random Forest Regressor ---")
print("평균제곱오차", mean_squared_error(y_test, rf_preds))

--- Random Forest Regressor ---
평균제곱오차 0.45312013844444193